name: ingarss-workshop-2024
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - rasterio
  - rioxarray
  - odc-stac
  - pip:
    - aiohttp
    - cartopy
    - dask
    - fsspec
    - geopandas
    - lonboard  
    - matplotlib
    - pystac-client
    - scikit-learn
    - xarray[complete]
    - jupyterlab
    - tqdm